servers:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jreihane
    password: DontTryComeIn123  
    driver-class-name: oracle.jdbc.driver.OracleDriver

cors-conf:
  allowed-origin: http://localhost:8091